### ISSUE TITLE
I've created an alternative version

### ISSUE THREAD

**Issue by flatsiedatsie** [ekymoz/homeRoughEditor#32]
In order to integrate this wonderful project into an open source privacy protecting smart home controller, [Candle](https://www.candlesmarthome.com), I modified your code a bit. I've added a number of new features that were on your wish list, so perhaps (some of) these changes could be integrated back into the original project. I wil be integrating my code into a Candle addon now, but I purposefully worked on it as a stand-alone project first so that it was as simple as possible to move code back to your project.

Code here:
https://github.com/createcandle/homeRoughEditor

Demo here:
https://createcandle.github.io/homeRoughEditor/

![floorplanner_test](https://github.com/ekymoz/homeRoughEditor/assets/805405/f30b379a-d4d8-4b42-8789-83a556554d77)

Big changes:
- Removed all dependencies on jQuery, Bootstrap, icons and other third party sources for privacy reasons.
- Made touch and mobile friendly (responsive).
- Expanded objects list (lots of new furniture).
- Users can now manage multiple floorplans.
- Object can be cloned, and their Z-position is moved 'to the top' when you drag them.
- I've put specific attention to allowing users to create fire safety maps.
- More...

I've hidden some features, but they can be revealed by having a `developer` tag in the html body. There is also an unfinished object layers feature which I've disabled for now.

I ran into a few minor bugs, which I fixed. But I've also introduced some new ones that I couldn't (quickly) solve. For example, I tried to get measurements to go into a separate `g` element, but they wouldn't properly recreate somehow. My 'solution' was to just only allow one measurement at a time. I also had trouble creating object outlines when scaling objects.

My code is far from clean, and the CSS is an unordered mess. But it works.

Again, thank you for your wonderful work! When I went looking to see if there was a projects I could use I never expected to find something so great.

**Comment by ekymo** [comment]
It is superb !

Managing several plans to make floors is cool, personally I would have sent a prompt to ask if the new floor had to recover the exterior walls (well, complicated... but oh well). Bravo for your adaptation.

Although not in a hurry, I am thinking of releasing a new version for Christmas.

Mobile, 3D, SVG or image objects directly in a JSON file...etc...

Finally, I hope.

Well done again.
Patrick

**Comment by flatsiedatsie** [comment]
Thanks :-) I'm glad you like it!

I've since integrated it into a plugin for the Candle smart home controller. That plugin has some more tiny improvements that I haven't backported...

Looking forward to the new version! Strange to think about Christmas already :-D
