### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by moeinserpico** [ekymoz/homeRoughEditor#4]
how can save and load model?

**Comment by tomaslachmann** [comment]
@moeinserpico a bit late, but still halpful.
create php file <?php 
$items = $_POST["item"];
$fp = fopen('results.json', 'w');
fwrite($fp, json_encode($items));
fclose($fp);
?>
create new option, with onclick="initHistory('yourValue);
create ajax callback with localstorage value, something like this:
$( "#lin" ).mousedown(function() {
  var item = JSON.parse(localStorage.getItem('history'));
  
    $.ajax({
    url : "something.php",
    type: "POST",
    data : {item:item},
    success: function(data)
    {
    }
});

edit func.js in Function inithistory write this code
 if (boot == "yourValue") {
      if (localStorage.getItem('history')) localStorage.removeItem('history'); 
      readTextFile("results.json", function(text){
        var data = JSON.parse(text);
        HISTORY.push(data);
        HISTORY[0] = JSON.stringify(data);
        localStorage.setItem('history', HISTORY[0]);
    });
    var historyTemp =  readTextFile("results.json", function(text){
      var data = JSON.parse(text);
      load(data.length-1, "boot");
      save("boot");
  });
    }
thats it

**Comment by RandomName-cmd** [comment]
I am a beginner in web Dev, can you please explain to me what you have done? @tomaslachmann
